### ISSUE TITLE
[Chore] 기초세팅

### ISSUE THREAD

**Issue by s9hn** [TeamRecorDream/RecorDream-AOS#1]
## 💡 Issue

기초세팅 중 임미다

## 📝 todo

- [ ] 패키지 구조화
- [ ] 스타일 가이드
- [ ] 이미지 에셋 
- [ ] 컬러
- [ ] BaseActivity 및 Fragment 생성
- [ ] Custom BottomNavigation Component 세팅
- [ ] util 생성(bindingAdapter, enqueueUtil, Dialog)
- [ ] Buildgradle 세팅
- [ ] theme 세팅
