### ISSUE TITLE
[FEAT] 2차 Qa 쳐내기

### ISSUE THREAD

**Issue by cbj0010** [TeamRecorDream/RecorDream-Aos#106]
## 💡 Issue
여러 Qa이슈들을 처리할 것 입니당

## 📝 todo

- [x] 세후니꺼 노트 갱신 안되던거 고침여
- [x] 인스타 없을 때 공유 막기 해야될 듯
- [x] 로딩뷰 넣어볼게요
- [ ] 기록하기 뷰에서 캘린더 클릭하면 왜 터지냐 ?
- [ ] 왜 같은 코드인데 특정 핸드폰에서는 앱이 로그인 및 설치가 안되는거지?
- [ ]  Crashlytics 심기
