### ISSUE TITLE
[Fix] 마이페이지 잡다한 기능 이슈 수정

### ISSUE THREAD

**Issue by cbj0010** [TeamRecorDream/RecorDream-Aos#12]
## 💡 Issue
mypage에서 요상한 기능들을 수정합니당

## 📝 todo

- [ ] bottomsheet값 사라지지 않도록
- [x] bottomsheet에서 값 수정하고 나서 cl 클릭했을 때 클릭 안되도록
- [ ] 키보드 enter클릭시 닉네임 200
