### ISSUE TITLE
[Layout] 보관함 뷰 

### ISSUE THREAD

**Issue by cbj0010** [TeamRecorDream/RecorDream-Aos#13]
## 💡 Issue
보관함 뷰 xml작업 할 것 입니다.

## 📝 todo

- [ ]보관함 list랑 grid 보여줄 framgent생성
- [ ]linearlist생성
- [x] list_grid생성
- [x] 위에 선택 넣기
- [x] 상단 바 만들기
- [ ] itemdecoration적용
- [ ] 아이콘 어떻게 넣을건지 생각
- [ ] tag 만들기
