### ISSUE TITLE
[Inflate] 로그인 뷰

### ISSUE THREAD

**Issue by s9hn** [TeamRecorDream/RecorDream-Aos#16]
## 💡 Issue

ㅈㄱㄴ

## 📝 todo

- [x] Manifest 세팅
- [x] setting.gradle에 코드 추가
- [x] build.gradle 에 카카오 SDK추가
- [x] 액티비티 코드에서 해시키, Manifest의 패키지명 확인 -> 카카오디벨로퍼 - 플랫폼등록
- [x] 카카오디벨로퍼 - 애플리케이션 추가
- [x] 카카오디벨로퍼 - 카카오로그인 활성화 ON
- [x] Activity 코드구현
- [x] string.xml, nativeKey 추가
- [x] Manifest 카카오로그인 추가
- [x] 토큰관리 클래스 생성
