### ISSUE TITLE
[Inflate] mypage 

### ISSUE THREAD

**Issue by cbj0010** [TeamRecorDream/RecorDream-Aos#19]
## 💡 Issue
버튼 눌렀을 경우 어쩌고 , bottomsheet

## 📝 todo

- [ ] name edit 눌렀을 경우
- [ ] 푸시알림 토글 켜졌을 경우 색상 바뀌게
- [ ] 푸시알림 토글 켜졌을 경우에 시간설정 부분 배경 바뀌도록
- [ ] 시간 설정 후 값 전달하기
