### ISSUE TITLE
[Layout] 상세보기 뷰 레이아웃

### ISSUE THREAD

**Issue by urjimyu** [TeamRecorDream/RecorDream-Aos#20]
## 💡 Issue

- 상세보기 뷰 레이아웃 만들기
- 끌어내리는 모양으로 만드는 거 고민해보기
- 팝업창 레이아웃 만들기
## 📝 todo

- [x] 상세보기 뷰 기본 화면 레이아웃
- [x] 더보기 눌렀을 때 바텀시트 레이아웃
- [x] 삭제하기 dialog 레이아웃
