### ISSUE TITLE
[Inflate] 상세보기 뷰

### ISSUE THREAD

**Issue by urjimyu** [TeamRecorDream/RecorDream-AOS#20]
## 💡 Issue

- 상세보기 뷰에서 인스타 스토리 공유 기능 구현하고 서버에서 받은 정보에 맞는 정보들을 각각 상단과 탭에 띄우기
- 바텀시트랑 다이얼로그 구현
## 📝 todo

- [ ] ... 누르면 바텀시트 올라오게 만들기
- [ ] 삭제하기 버튼 누르면 취소 재확인 다이얼로그 뜨도록 구현
- [ ] 공유하기 버튼 누르면 인스타 스토리 공유하기 구현
