### ISSUE TITLE
[Layout] 홈뷰 레이아웃

### ISSUE THREAD

**Issue by urjimyu** [TeamRecorDream/RecorDream-Aos#21]
## 💡 Issue

- 메인 안에 들어가는 뷰페이저 부분 레이아웃 작업 할 예정!
## 📝 todo

- [x] 뷰페이저 아이템 디자인
- [x] 뷰페이저 어댑터 만들고 연결
- [ ] 10개씩 보이게 설정
- [ ] 랜덤으로 보이게 설정
