### ISSUE TITLE
[Inflate] 홈뷰 기능 구현

### ISSUE THREAD

**Issue by urjimyu** [TeamRecorDream/RecorDream-Aos#24]
## 💡 Issue

홈 뷰 기능 구현 작업 예정입니다
## 📝 todo

- [ ] 새로고침 갱신 기능
- [ ] 닉네임 받아오기
- [ ] 기록 유형에 따라 다르게 카드가 뜨도록 적용(녹음 유무 등)
- [x] 버튼과 다른 뷰 연결
