### ISSUE TITLE
[Inflate] 상세보기 뷰 녹음 기능 구현

### ISSUE THREAD

**Issue by urjimyu** [TeamRecorDream/RecorDream-Aos#25]
## 💡 Issue

상세보기에서 녹음 관련 기능을 구현할 예정입니다.
## 📝 todo

- [ ] 녹음 재생 눌렀을 때 아이콘 바뀌게 설정
- [ ] 녹음 시간 받아와서 띄우기
- [ ] 프로그레스 바 커스텀하기(시간에 맞게 바가 움직이게 구현)
- [ ] 녹음 유무에 따라 녹음기 보이게/안 보이게 설정하기
- [ ] 녹음 파일 받아와서 재생/정지/다시 재생 적용되도록 하기
