### ISSUE TITLE
[Inflate] 상세보기 뷰 기능 구현

### ISSUE THREAD

**Issue by urjimyu** [TeamRecorDream/RecorDream-Aos#26]
## 💡 Issue

녹음 기능 외의 기능들도 구현
## 📝 todo

- [x] 노트 띄우기
- [x] 나의 꿈 기록 띄우기
- [x] 바텀 시트 띄우기
- [x] 다이얼로그 띄우기(삭제하기)
- [ ] 자연스럽게 화면 전환 되도록 설정하기
- [x] 취소 버튼 기능 구현
