### ISSUE TITLE
[Inflate] 보관함 뷰

### ISSUE THREAD

**Issue by cbj0010** [TeamRecorDream/RecorDream-Aos#33]
## 💡 Issue
보관함 뷰 기능구현

## 📝 todo

- [x] 아이콘 클릭시 아이콘에 맞게 기록 정렬
- [x] 그리드 눌렀을 때 그리드 뷰
- [x] list 뷰 눌렀을 때 list view
- [x] grid itemdecoration
- [x] list itemdecoration
- [x] item decoration
- [x] itemlist databinding적용한거 viewmodel생성
