### ISSUE TITLE
[Inflate] 글작성하는 뷰 

### ISSUE THREAD

**Issue by cbj0010** [TeamRecorDream/RecorDream-AOS#34]
## 💡 Issue
witre에서 기능을 구현할 것 입니다

## 📝 todo

- [ ] 감정이모티콘 클릭시 색 변환하기
- [ ] 음성녹음 dialog붙이기
- [ ] 글 쓴거 intent로 넣어주기
- [ ] 해시태그 클릭시 색 변환
- [ ] 저장하기 조건달기
