### ISSUE TITLE
[Remote] 상세보기 뷰

### ISSUE THREAD

**Issue by urjimyu** [TeamRecorDream/RecorDream-AOS#38]
## 💡 Issue

상세보기 뷰 서버 붙이기!
## 📝 todo

- [ ] 상단 꿈 카드 부분 서버 통신 
- [ ] 정보가 null 값일 때 처리 설정해주기
- [ ] int로 받는 걸 image나 string으로 변환해주기
- [ ] 탭 부분 녹음 유무에 따라 설정해주기
- [ ] 녹음 파일 유무에 따른 재생기능 구현하기
- [ ] 서버 통신으로 탭에 맞는 내용 집어넣기
- [ ] 바텀 시트 삭제하기
- [ ] 바텀 시트 수정하기 -> 기록하기뷰랑 이어주기
