### ISSUE TITLE
[Remote] 홈 뷰 서버통신

### ISSUE THREAD

**Issue by urjimyu** [TeamRecorDream/RecorDream-AOS#39]
## 💡 Issue

홈 뷰 서버 붙이기!
## 📝 todo

- [ ] 카드에 맞는 정보 불러오기
- [ ] null인 경우 따로 처리하기
- [ ] int로 받는 애들 image, string 등으로 변환해서 잘 넣어주기
