### ISSUE TITLE
[Layout] 상세보기 뷰

### ISSUE THREAD

**Issue by urjimyu** [TeamRecorDream/RecorDream-AOS#4]
## 💡 Issue

상세보기 뷰 xml 작업을 할 것입니다.
## 📝 todo

- [ ] 동그란 감정 아이콘 넣기
- [ ] 탭 레이아웃, 뷰페이저 적용
- [ ] 해시태그 칩 자리 만들어놓기
- [ ] 레코드림 마크(하단에 고정) 적용
- [ ] 더보기 바텀시트 만들기
