### ISSUE TITLE
[Inflate] 기록하기 뷰_음성녹음

### ISSUE THREAD

**Issue by s9hn** [TeamRecorDream/RecorDream-Aos#44]
## 💡 Issue

- 음성녹음 바텀다이얼로그 기능구현

## 📝 todo

- [x] 권한 요청
- [x] 음성 녹음 시작
- [x] 음성 녹음 중단
- [x] 음성 녹음 재생
- [x] 음성 녹음 중지
- [x] 음성 녹음 초기화
- [x] 외부 터치 영역 X
- [x] 프로그래스바 터치 X
