### ISSUE TITLE
[INFLATE] 상세보기 뷰 인스타 스토리 공유 기능 구현

### ISSUE THREAD

**Issue by urjimyu** [TeamRecorDream/RecorDream-Aos#45]
## 💡 Issue

상세보기 뷰에서 다이얼로그의 공유하기를 눌렀을 때 레코드림 템플릿에 맞게 인스타 스토리 공유가 이루어지도록 하는 기능 구현.
## 📝 todo

- [x] 레코드림 커스텀 템플릿 디자인
- [x] 스토리 공유시 스크린샷 캐시에 저장
- [x] 인스타 스토리 공유로 넘어가게 기능 구현
