### ISSUE TITLE
[FEAT] 안드 자체 qa 수정사항

### ISSUE THREAD

**Issue by cbj0010** [TeamRecorDream/RecorDream-Aos#84]
## 💡 Issue
안드 자체 qa

## 📝 todo

보관함뷰
- [x] 리스트 간격 조정 필요
- [x] 기록작성 완료 했을 때 보관함 뷰 갱신

전체
- [x] 다크모드 막기
- [x] 가로모드 막기

푸시알림
- [x] 알림 왔을 때 로고 안보이는거 수정
- [x] 알림 클릭시 기록하기 뷰로 이동

마이페이지뷰
- [x] 로그아웃 시 토큰 초기화 필요
